<?php

/**
 * @file Provides a slide-out box which presents a link to the next piece of content
 *
 * @author Rob Knight <http://drupal.org/user/36475>
 */

/**
 * Implementation of hook_permission()
 */
function slidebox_permission() {
  return array(
    'administer slidebox' => array(
      'title' => t('Administer slidebox'),
      'description' => t('Configure settings for the slidebox module')
    )
  );
}

/**
 * Implementation of hook_menu()
 */
function slidebox_menu() {
  $items = array();
  $items['admin/config/system/slidebox'] = array(
    'title' => 'Slidebox',
    'description' => 'Configure the slidebox module',
    'access arguments' => array('administer slidebox'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('slidebox_admin_settings'),
    'file' => 'slidebox.admin.inc'
  );
  return $items;
}

/**
 * Implementation of hook_theme()
 */
function slidebox_theme($existing, $type, $theme, $path) {
  return array(
    'slidebox_field' => array(
      'variables' => array('nid' => NULL, 'title' => NULL),
      'template' => 'slidebox'
    )
  );
}

/**
 * Implementation of hook_node_view()
 */
function slidebox_node_view($node, $view_mode, $langcode) {
  $node_details = slidebox_data($node, $view_mode);

  // See if any other module wants to alter or erase $node_details
  drupal_alter('slidebox_data', $node_details, $view_mode);

  if(!empty($node_details['nid'])) {
    drupal_add_js(array('slidebox' => slidebox_js_settings()), "setting");

    $node->content['slidebox'] = array(
      '#markup' => theme('slidebox_field', $node_details),
      '#weight' => 99,
    );
    $node->content['slidebox_trigger'] = array(
      '#markup' => '<div id="slidebox_trigger"></div>',
      '#weight' => 99
    );
  }
}

/**
 * Implementation of hook_init()
 */
function slidebox_init() {
  drupal_add_css(drupal_get_path('module', 'slidebox') . '/css/slidebox.css',
                 array('group' => CSS_DEFAULT, 'every_page' => TRUE));

  drupal_add_js(drupal_get_path('module', 'slidebox') . '/js/slidebox.js',
                array('group' => JS_DEFAULT, 'every_page' => TRUE));
  drupal_add_js('misc/jquery.cookie.js');
}

/**
 * Return data for slidebox
 * @TODO Add support for entities
 */
function slidebox_data($node, $view_mode) {
  if ($view_mode != 'full' || !node_is_page($node) || !in_array($node->type, variable_get('slidebox_content_types'))) {
    return FALSE;
  }

  $result = db_query("SELECT nid, title FROM {node} WHERE created < :created AND type = :type AND status = :status ORDER BY created DESC LIMIT 1",
                     array(':created' => $node->created, ':type' => $node->type, ':status' => 1));

  $slidebox = is_object($result) ? $result->fetchAssoc() : FALSE;

  if (TRUE != node_access('view', node_load($slidebox['nid']))) {
    return FALSE;
  }

  return $slidebox;
}

/**
 * Returns settings to be used by JavaScript
 */
function slidebox_js_settings() {
  return array(
    'showTime' => variable_get('slidebox_show_time', 300),
    'hideTime' => variable_get('slidebox_hide_time', 100)
  );
}

